### ISSUE TITLE
Not able to load libc

### ISSUE THREAD

**Issue by FrankSpierings** [Gallopsled/pwntools-write-ups#36]
While trying to load libc, I receive the following error:

```
>>> ELF('/lib/i386-linux-gnu/i686/cmov/libc.so.6')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/__init__.py", line 65, in __init__
    self._populate_got_plt()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/__init__.py", line 250, in _populate_got_plt
    rel_plt = next(s for s in self.sections if s.header.sh_info == self.sections.index(plt))
StopIteration
```

Any idea how to fix this?

Installed the latest version of capstone.
Running on Kali.

**Comment by zachriggle** [comment]
Does this repro on Binjitsu? (Binjit.su)

**Comment by supercsq** [comment]
I got the same problem ,i install pwntools  with pip install pwntools in python 2.7 ,how to fix it?

kali rolling x86

**Comment by supercsq** [comment]
only work in kali 2.0  not rolling version

**Comment by supercsq** [comment]
i think  the version of glibc in kali rolling is too high

**Comment by zachriggle** [comment]
Please provide a copy of the binary that causes this issue

**Comment by supercsq** [comment]
here it is  
https://github.com/supercsq/libc

**Comment by deveshm** [comment]
running `sudo pip install pwntools --upgrade` made it work for me
the error might have to do with something about installing pwntools as a low level user rather than root

**Comment by FrankSpierings** [comment]
I forgot this was still open.
